K8s 1.7 update changes. Make kubelet more customizable.
vmware/ansible-coreos-kubelet pull request #4
Opened 2017-07-25 06:12 UTC by puneetkatyal

* Support custom secure port for API server
* Make kubelet options more customizable
* Use --pod-manifest-path instead of deprecated --config option
* Use new options: KUBELET_IMAGE_TAG, KUBELET_IMAGE_URL & RKT_RUN_ARGS

2017-08-11 21:40 UTC, imkin requested changes

2017-08-11 21:40 UTC, imkin commented on defaults/main.yml
> +kubelet_version: "v1.7.0_coreos.0"
v1.7.3_coreos.0 seems to be now available. This has a fix for https://github.com/kubernetes/kubernetes/issues/48848

2017-08-11 21:40 UTC, imkin commented on defaults/main.yml
>  kubelet_aci: "quay.io/coreos/hyperkube"
this should be kubelet_image_url now?

2017-08-11 22:05 UTC, imkin commented
Is it ok to squash the commits?

2017-08-11 23:59 UTC, puneetkatyal commented on defaults/main.yml
>  kubelet_aci: "quay.io/coreos/hyperkube"
No, this is only an ansible variable. We set Kubelet environment variables in `templates/kube.env.j2`

2017-08-12 00:01 UTC, puneetkatyal commented on defaults/main.yml
> +kubelet_version: "v1.7.0_coreos.0"
That issue is for GCE. Also, I've only tested v1.7.0 so would like to leave the default to that version.
We can always update this from the base repo as needed.

2017-08-12 00:02 UTC, puneetkatyal commented
The commits are more or less separate, so it's better to leave them as is for history.

2017-08-12 00:05 UTC, imkin commented on defaults/main.yml
> +kubelet_version: "v1.7.0_coreos.0"
The version here does not matter actually we can override it from the coreos-ansbile vars.

2017-08-12 00:08 UTC, imkin commented
It is difficult to get the context of the commits if they are not squashed. if they are all different, then there should have been different PR's.

2017-08-14 14:55 UTC, puneetkatyal commented
@imkin The PR description provides enough context to the individual commits so they can be part of the same PR. I would prefer these get merged as individual commits and not as a squashed one to provide details on individual changes.

2017-08-14 21:49 UTC, imkin approved these changes

2017-08-14 21:49 UTC, merged