Remove deprecated options: --api-servers, --register-schedulable
vmware/ansible-coreos-kubelet pull request #6
Opened 2017-10-11 00:14 UTC by puneetkatyal

- Use server info from kubeconfig instead of deprecated '--api-servers' option
- Master nodes are made unschedulable by default using taints --
  https://github.com/kubernetes-incubator/kube-aws/issues/286#issuecomment-275587871

2017-10-11 15:41 UTC, naveens approved these changes

2017-10-11 23:39 UTC, imkin requested changes

2017-10-11 23:39 UTC, imkin commented on templates/kubelet.service
> +  --kubeconfig=/etc/kubernetes/apiserver-kubeconfig.yaml \
Did we add this file somewhere? I do not see it anywhere.

2017-10-12 03:55 UTC, puneetkatyal commented on templates/kubelet.service
> +  --kubeconfig=/etc/kubernetes/apiserver-kubeconfig.yaml \
https://github.com/vmware/ansible-coreos-kubernetes-master/pull/13

Similar to how worker-kubeconfig.yml is added in ansible-coreos-kubernetes-minion role

2017-10-13 17:48 UTC, imkin commented on templates/kubelet.service
> +  --kubeconfig=/etc/kubernetes/apiserver-kubeconfig.yaml \
Seems to be an antipattern. This role is not complete on its own and is now dependent on minion and master roles.

2017-10-13 17:49 UTC, imkin approved these changes

2017-10-16 14:27 UTC, merged